### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Khapra** [IceWhaleTech/CasaOS#1002]
**Describe the bug**
CasaOS v0.4.3. The cloud locations in Files app is not persistent. I need to add them after every restart.

**To Reproduce**
1. Go to 'Files' app.
2. Click on '+' under 'Location'
3. After adding, Restart.
4. The cloud location is not there.

**Expected behavior**
Once the cloud storage is added, it should show under locations after restart, even if i have to login again.

**Desktop (please complete the following information):**
 - OS: [Raspberry Pi OS 5.15]
 - Browser [Brave]

**Comment by raller1028** [comment]
Fixed, can you update v0.4.3 again by command?
Upgrade command: `curl -fsSL https://get.casaos.io/update | bash`

**Comment by Khapra** [comment]
> Fixed, can you update v0.4.3 again by command?
> Upgrade command: `curl -fsSL https://get.casaos.io/update | bash`

The update process is getting stuck at "setup-app-management.sh" - INFO Target version already installed.

**Comment by raller1028** [comment]
![Image](https://user-images.githubusercontent.com/57336867/231736796-5d723d9e-72ea-471b-bbff-779271d65f3d.png)

We've tested it and it's working. It's possible that the update is stuck due to a network jam, can you try it again?

**Comment by Khapra** [comment]
Issue still persists for me. Have tried restarting few times. Please let me know if any further info or logs are required.

**Comment by Khapra** [comment]
> 
> 
> ![Image](https://user-images.githubusercontent.com/57336867/231736796-5d723d9e-72ea-471b-bbff-779271d65f3d.png)
> 
> We've tested it and it's working. It's possible that the update is stuck due to a network jam, can you try it again?

Issue still persists for me. Have tried restarting few times. Please let me know if any further info or logs are required.
