### ISSUE TITLE
[Bug] Random new drive found message displayed

### ISSUE THREAD

**Issue by riclucio** [IceWhaleTech/CasaOS#2287]
**Describe the bug**

> My CasaOS dashboard started to show the message "Found a new drive" randomly, with a "NaN / NaN undefined" message in the size. 
> Clicking "Storage Manager" only shows storage dialog after multiple clicks, and the dialog doesn't show any new storage.
> The X button to dismiss also doesn't work.

**Screenshots**
![Image](https://github.com/user-attachments/assets/0bcc3439-3382-44c3-b492-9d5e308a29bd)

**Desktop (please complete the following information):**

```
 - OS (Desktop): MacOS, (Server): Ubuntu 24.04.2 LTS aarch64
 - Browser: Brave
 - Version: 1.80.113
 - Server Host: Orange Pi 5 Max
 - Kernel: 6.1.0-1025-rockchip
 - CasaOS version: v0.4.15
```

**System Time**
```
ubuntu@homelab:~$ timedatectl
               Local time: Mon 2025-06-30 16:14:16 UTC
           Universal time: Mon 2025-06-30 16:14:16 UTC
                 RTC time: Mon 2025-06-30 16:14:17
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management

[casaos-user-service.log](https://github.com/user-attachments/files/20983921/casaos-user-service.log)
[casaos-service.log](https://github.com/user-attachments/files/20983920/casaos-service.log)
[casaos-local-storage.log](https://github.com/user-attachments/files/20983922/casaos-local-storage.log)
[casaos-gateway.log](https://github.com/user-attachments/files/20983923/casaos-gateway.log)
[casaos-app-management.log](https://github.com/user-attachments/files/20983924/casaos-app-management.log)

```

**Comment by blindmanonacid** [comment]
Just to say that the same happened here and I haven't added drives or even rebooted the device for a long time. Why is this happening to several people now?

**Comment by forkymcforkface** [comment]
Check

ls /mnt

If there are any folders there that should not be, delete it. The notification will go away.

**Comment by Crazygiscool** [comment]
> Check
> 
> ls /mnt
> 
> If there are any folders there that should not be, delete it. The notification will go away.

I kinda resetted it, but I’m sure that would’ve worked, thanks

**Comment by songmaker** [comment]
I found that it was a SWAP issue, and with the lsblk command I found that the size of zram0 is exactly the same as the size mentioned in the message "Found a new drive".

<img width="557" height="344" alt="Image" src="https://github.com/user-attachments/assets/7a725ad6-8d13-49d2-a5fe-a43de4299e6d" />

But I don't know how to change it to prevent casaos from reading zram0's information. So I asked the AI, and they said that you can manually configure udev rules to block zram events, but I tried it and it didn't work.
```
# Create a rule file:
sudo nano /etc/udev/rules.d/99-ignore-zram.rules
Write the following:
# Ignore the add event for zram0 devices (to prevent misidentification by CasaOS)
KERNEL=="zram0", ACTION=="add", ENV{UDISKS_IGNORE}="1", ENV{ID_MM_DEVICE_IGNORE}="1"
# Can be extended to ignore all zram:
KERNEL=="zram[0-9]*", ACTION=="add", ENV{UDISKS_IGNORE}="1", ENV{ID_MM_DEVICE_IGNORE}="1"
# After saving, reload the udev rules:
sudo udevadm control --reload-rules
sudo udevadm trigger
# Then restart CasaOS:
sudo systemctl restart casaos
```

**Comment by forkymcforkface** [comment]
> I found that it was a SWAP issue, and with the lsblk command I found that the size of zram0 is exactly the same as the size mentioned in the message "Found a new drive".
> 
> <img alt="Image" width="557" height="344" src="https://private-user-images.githubusercontent.com/30719753/492028373-7a725ad6-8d13-49d2-a5fe-a43de4299e6d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg2NDY5MjcsIm5iZiI6MTc1ODY0NjYyNywicGF0aCI6Ii8zMDcxOTc1My80OTIwMjgzNzMtN2E3MjVhZDYtOGQxMy00OWQyLWE1ZmUtYTQzZGU0Mjk5ZTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTIzVDE2NTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNWMxNDIzZDdmN2EwZTcwZmFiMzAzMDdiYzZiNzMwYWE0ZGU0MTc2YzliNzkzY2ZlNDllOTM3MzkzYTRhNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.etm_Cfia0ZDCxr8PkqC7Fh5TTEywfr330Y3yQiOcWno">
> But I don't know how to change it to prevent casaos from reading zram0's information. So I asked the AI, and they said that you can manually configure udev rules to block zram events, but I tried it and it didn't work.
> 
> ```
> # Create a rule file:
> sudo nano /etc/udev/rules.d/99-ignore-zram.rules
> Write the following:
> # Ignore the add event for zram0 devices (to prevent misidentification by CasaOS)
> KERNEL=="zram0", ACTION=="add", ENV{UDISKS_IGNORE}="1", ENV{ID_MM_DEVICE_IGNORE}="1"
> # Can be extended to ignore all zram:
> KERNEL=="zram[0-9]*", ACTION=="add", ENV{UDISKS_IGNORE}="1", ENV{ID_MM_DEVICE_IGNORE}="1"
> # After saving, reload the udev rules:
> sudo udevadm control --reload-rules
> sudo udevadm trigger
> # Then restart CasaOS:
> sudo systemctl restart casaos
> ```

This script should fix the issue. lmk

```
#!/bin/bash
#
# CasaOS Ghost Cleaner
#
# SAFETY NOTICE:
# ----------------------------------------------------
# This script does NOT unmount, touch, or delete any
# user data or mounted drives.
#
# It ONLY:
#   1. Cleans leftover phantom "loop" or zero-size
#      notifications from CasaOS user.db (events table).
#   2. Removes truly empty folders left in /mnt.
#   3. Detaches orphaned loop devices whose backing
#      files no longer exist.
#
# No partitions, mounts, or actual data are modified.
# ----------------------------------------------------

DB="/var/lib/casaos/db/user.db"

# Ensure sqlite3 is available
if ! command -v sqlite3 >/dev/null 2>&1; then
    echo "sqlite3 not found, installing..."
    apt-get update -qq
    apt-get install -y sqlite3
fi

if [ ! -f "$DB" ]; then
    echo "CasaOS user.db not found at $DB"
    exit 1
fi

# --- 1. Detach orphan loops ---
while IFS= read -r line; do
    loopdev=$(echo "$line" | cut -d: -f1)
    file=$(echo "$line" | sed -n 's/.*(\(.*\)).*/\1/p')
    if [ "$file" = "(deleted)" ] || [ ! -e "$file" ]; then
        echo "Detaching orphan loop: $loopdev"
        losetup -d "$loopdev"
    fi
done < <(losetup -a)

# --- 2. Clean phantom loop events from CasaOS DB ---
ACTIVE_LOOPS=$(losetup -a | cut -d: -f1)
SQL="DELETE FROM events WHERE name LIKE 'local-storage:disk:added' AND properties LIKE '%/dev/loop%'"

for loop in $ACTIVE_LOOPS; do
    dev=$(basename "$loop")
    SQL+=" AND properties NOT LIKE '%/$dev%'"
done

sqlite3 "$DB" "$SQL"
sqlite3 "$DB" "DELETE FROM events WHERE properties LIKE '%\"size\":\"0\"%';"

# --- 3. Remove empty /mnt folders ---
for d in /mnt/*; do
    [ -d "$d" ] || continue
    if [ -z "$(ls -A "$d")" ]; then
        echo "Removing empty folder: $d"
        rm -rf "$d"
    fi
done

# Restart CasaOS user service so UI reflects changes
systemctl restart casaos-user-service

```

**Comment by forkymcforkface** [comment]
I submitted this [PR #256](https://github.com/IceWhaleTech/CasaOS-UI/pull/256)

**Comment by songmaker** [comment]
> I submitted this   我提交了这个[PR #256](https://github.com/IceWhaleTech/CasaOS-UI/pull/256)

@forkymcforkface Hello!
I found out that the PR #256 you submitted has been merged into mainline and released, so I used the command "curl -fsSL https://get.casaos.io/update | sudo bash" updated the UI of casaos. The UI did update, but the message "Found a new drive" was still there. Although it can be turned off, it still exists after refreshing. 

Maybe your changes didn't work? Maybe you can also update the UI to see if it fixes the problem.

**Comment by songmaker** [comment]
> The X button to dismiss also doesn't work.

@riclucio @blindmanonacid  Hello!
Try using the command "curl -fsSL https://get.casaos.io/update | sudo bash" updated the UI of casaos. The X button is working fine, but the message "Found a new drive" still appears after refreshing on my machine. 

I would like to know how your UI is doing after the update.
