### ISSUE TITLE
[Alpha][Bug]: SmartCTL errors on CasaOS logs (on VMs)

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#394]
### What happened?

We got a lot of errors like the following one both for VMs under ESXi and Proxmox.
Expected behavior: have a condition in case of VMs to stop the SmartCTL from constantly checking for disk data and re enable it in case of existence of another drive (with SMART) apart from boot drive added to CasaOS. (It was originally founded on the previous release)
```
{"level":"error","ts":1658290120.1887748,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290125.184332,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290130.1847856,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290135.1888332,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290140.184859,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290145.188838,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290150.1887355,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290155.193259,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290160.1848269,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290165.1889205,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290170.1888192,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290175.18838,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290180.1887264,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290185.188886,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290190.1847312,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290195.192836,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290200.1843646,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290205.1847312,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290210.1807647,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290215.1890934,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290220.1847749,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290225.1883814,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290230.188879,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290235.188784,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290240.1847968,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290245.1888533,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290250.188717,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290255.1883092,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290260.1848254,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290265.192808,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290270.188788,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290275.1890829,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290280.1887157,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290285.1847696,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290290.1887865,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290295.1888638,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290300.192882,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290305.1889338,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290310.1847181,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290315.1887877,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290320.1848128,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290325.1888647,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290330.1887493,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290335.1850114,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290340.1887398,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290345.1888006,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290350.1888058,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290355.1888416,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290360.192863,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290365.1888251,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290370.1847641,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290375.1843774,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290380.184853,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290385.1844404,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290390.18878,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290395.1890097,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290400.1887991,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290405.1889114,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290410.1888292,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290415.184869,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290420.1887655,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290425.1849036,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290430.1888201,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290435.1889904,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290440.1928647,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290445.184819,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290450.18827,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290455.1854224,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290460.188729,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290465.180751,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290470.1930218,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290475.1887648,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290480.1887722,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290485.1888812,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290490.1848552,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290495.1843755,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290500.1928797,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290505.1887937,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290510.1848156,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290515.1851676,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290520.1888077,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290525.1808972,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290530.1887994,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290535.188794,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290540.1887972,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290545.1888046,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290550.188809,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290555.1888213,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290560.1889071,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290565.1888833,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290570.1847239,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290575.1854236,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290580.1847603,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290585.1888692,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290590.184854,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290595.188815,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290600.1806946,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290605.1928506,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290610.184838,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290615.1888874,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290620.1848,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290625.188809,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290630.1882966,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290635.192938,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290640.1888754,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290645.1888063,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290650.1843343,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290655.1888123,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290660.1883273,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290665.1888125,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290670.1842842,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290675.1889157,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290680.192843,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290685.1883113,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290690.1882799,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290695.1933706,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290700.1843154,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290705.1888916,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290710.1843176,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290715.1843452,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290720.188289,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290725.1883914,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290730.1883178,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290735.188429,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290740.1883585,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
{"level":"error","ts":1658290745.1923707,"msg":"failed to  exec shell ","err":"smartctl exec error","func":"service.(*diskService).SmartCTL","file":"/source/service/disk.go","line":61}
```
Reporter: @AuthorShin @zarevskaya 

### Screenshots

https://media.discordapp.net/attachments/987294590627373066/1000020049169498173/Capture_decran_du_2022-07-22_14-42-16.png?width=1292&height=790

**Comment by tigerinus** [comment]
@AuthorShin @zarevskaya - can you confirm the path of `smartctl`?

**Comment by zarevskaya** [comment]
I have no more disk for the moment to test. Sorry :(

**Comment by AuthorShin** [comment]
@JohnGuan You see that's why we need a server testing team (each member a VM or VPS) so that later developers can easily access and reproduce the bugs.

**Comment by AuthorShin** [comment]
@JohnGuan John, I think you can get a sponsor, with 5.5k stars you can easily get DigitalOcean to sponsor CasaOS.

**Comment by tigerinus** [comment]
@JohnGuan 

The first question has to be anwsered: Is `smartctl` command in the path?

> > @JohnGuan You see that's why we need a server testing team (each member a VM or VPS) so that later developers can easily access and reproduce the bugs.
> 
> @tigerinus Do you have a solution for this problem? Are there any recommendations you can give for the test environment? Recommended configurations for virtual machines or tutorials for getting free cloud servers (like the free tier of Oracle Cloud)? Also is there a more efficient way to get error messages and environment information?

**Comment by llwaini** [comment]
`smartctl` has been fixed on CasaOS V0.3.6, please try it on 0.3.6

**Comment by AuthorShin** [comment]
@zarevskaya Should be able to confirm the fix since I have no access to VM anymore.

**Comment by zarevskaya** [comment]
I sleep now but I try when I'm wake up 👍

**Comment by AuthorShin** [comment]
@zarevskaya Hey man, You are not awake yet? :D

**Comment by zarevskaya** [comment]
> @zarevskaya Hey man, You are not awake yet? :D

My apologies, when I answer half asleep, it slips out of my head.

Fixed here.

But I have an other error.

![Screenshot_2022-11-27-03-39-05-58_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/60230221/204116807-d5dc5234-15a9-4135-ab94-9fc78982f3eb.jpg)

I open a new issue?

**Comment by AuthorShin** [comment]
I already reported this new one here: https://github.com/IceWhaleTech/CasaOS/issues/715
Thank you for checking it, I think we can close it for now until we encounter the same bug again.

**Comment by oijkn** [comment]
I notice recurrent errors in the logs concerning `smartctl` : 
```sh
Jan 22 15:13:20 casaos casaos-local-storage[612]: /usr/sbin/smartctl -a -n /dev/sda -j
Jan 22 15:13:20 casaos casaos-local-storage[612]: smartctl 7.2 2020-12-30 r5155 [aarch64-linux-5.15.84-v8+] (local build)
Jan 22 15:13:20 casaos casaos-local-storage[612]: Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org
Jan 22 15:13:20 casaos casaos-local-storage[612]: =======> INVALID ARGUMENT TO -n: /dev/sda
Jan 22 15:13:20 casaos casaos-local-storage[612]: =======> VALID ARGUMENTS ARE: never, sleep[,STATUS], standby[,STATUS], idle[,STATUS] <=======
Jan 22 15:13:20 casaos casaos-local-storage[612]: Use smartctl -h to get a usage summary
Jan 22 15:13:20 casaos casaos-local-storage[612]: 2023-01-22T15:13:20.108+0100        error        failed to exec shell - smartctl exec error        {"func": "service.(*diskService).Sm>
Jan 22 15:13:23 casaos systemd[1]: run-docker-runtime\x2drunc-moby-334592f86c1096d0132e927567accf83be31093a3e2212e064441fe0b36ebc29-runc.5HHtF9.mount: Succeeded.
Jan 22 15:13:40 casaos casaos-local-storage[612]: /usr/sbin/smartctl -a -n /dev/mmcblk0 -j
Jan 22 15:13:40 casaos casaos-local-storage[612]: smartctl 7.2 2020-12-30 r5155 [aarch64-linux-5.15.84-v8+] (local build)
Jan 22 15:13:40 casaos casaos-local-storage[612]: Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org
Jan 22 15:13:40 casaos casaos-local-storage[612]: =======> INVALID ARGUMENT TO -n: /dev/mmcblk0
Jan 22 15:13:40 casaos casaos-local-storage[612]: =======> VALID ARGUMENTS ARE: never, sleep[,STATUS], standby[,STATUS], idle[,STATUS] <=======
Jan 22 15:13:40 casaos casaos-local-storage[612]: Use smartctl -h to get a usage summary
Jan 22 15:13:40 casaos casaos-local-storage[612]: 2023-01-22T15:13:40.063+0100        error        failed to exec shell - smartctl exec error        {"func": "service.(*diskService).Sm>
```

**Comment by raller1028** [comment]
This issue is temporarily closed, if still have problems please reopen :)
